#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "Running pre-commit hook" 
echo "Current directory: $(pwd)" 

# Проверка кода линтером 
npm run lint:fix
npm run lint

# Unit-тесты 
npm run test 

# E2E-тесты 
# yarn test:e2e:headless

